server:
  servlet:
    context-path:
      /api/minesweeper
  port: 8080
management:
  endpoints:
    enabled-by-default: true
    web:
      base-path: /
spring:
  datasource:
    initialize: false
    driverClassName: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://bd82e129dba2bd:4f9c6641@us-cdbr-east-02.cleardb.com/heroku_e790c3d4b44aa06?reconnect=true"
    username: bd82e129dba2bd
    password: 4f9c6641
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    show-sql: true
    hibernate:
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        connection:
          release_mode: on_close